title: mmCEsim Publications
author:
  name: Wuqiong Zhao (Teddy van Jerry)
  email: contact@mmcesim.org
description: Explore publications of mmCEsim!

minima:
  social_links:
    twitter: mmcesim
    github: mmcesim
    youtube_channel: UCnYkaHcT9qM5QnbZbVLtEEQ
    youtube_channel_name: mmCEsim

theme: minima@fdc3aba23a1d59ad1d1f65f505693848c4b82fdf
plugins:
  - jekyll-feed
  - jekyll-seo-tag
