title: mmCEsim Publications
author:
  name: Wuqiong Zhao (Teddy van Jerry)
  email: contact@mmcesim.org
description: >
  Explore publications of mmCEsim!
  The application mmCEsim is a powerful tool
  to simulate millimeter wave (mmWave)
  channel estimation (CE) for both experts and learners.

minima:
  social_links:
    - { platform: github, user_url: "https://github.com/mmcesim" }
    - { platform: twitter, user_url: "https://twitter.com/mmcesim" }
    - { platform: youtube, user_url: "https://www.youtube.com/channel/UCnYkaHcT9qM5QnbZbVLtEEQ", title: "mmCEsim" }

remote_theme: jekyll/minima@master
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - scripts
